name: fintrack

services:
  portainer:
    image: portainer/portainer-ce:2.21.5
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  postgres:
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres/00-init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    restart: unless-stopped
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    restart: unless-stopped
    environment:
      ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
      - "18888:18888"
      - "4317:18889"
      - "4318:18890"

volumes:
  portainer_data:
  postgres_data:
  keycloak_data:
