global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Reflection;
global using System.Security.Claims;
global using System.Text.Json.Serialization;
global using CleanArch.Mediator.Primitives;
global using CleanArch.MinimalApis;
global using CleanArch.Persistence.Primitives;
global using CleanArch.Results.AspNetCore;
