distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: :4317
        http:
          endpoint: :4318

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal

compactor:
  compaction:
    block_retention: 24h

metrics_generator:
  registry:
    external_labels:
      source: tempo
