name: Trigger auto deployment for ca-ftrk-ledger-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-ftrk-ledger-api-AutoDeployTrigger-f1676619-d54f-43f9-9c05-fbb34a2a776f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAFTRKLEDGERAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAFTRKLEDGERAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAFTRKLEDGERAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}\services\ledger\src\Fintrack.Ledger.Api\Dockerfile
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.CAFTRKLEDGERAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAFTRKLEDGERAPI_REGISTRY_PASSWORD }}
          containerAppName: ca-ftrk-ledger-api
          resourceGroup: rg-shared
          imageToBuild: gabbium/ca-ftrk-ledger-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


