name: Publish Docker Images

on:
  release:
    types: [published]

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ledger-api
            image: gabbium/fintrack-ledger-api
            dockerfile: ./services/Ledger/src/Fintrack.Ledger.Api/Dockerfile

          - name: ledger-migrationservice
            image: gabbium/fintrack-ledger-migrationservice
            dockerfile: ./services/Ledger/src/Fintrack.Ledger.MigrationService/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from release tag
        id: ver
        run: |
          RAW="${{ github.event.release.tag_name }}"
          echo "raw=${RAW}" >> $GITHUB_OUTPUT
          echo "version=${RAW#v}" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392

      - name: Setup Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Docker Hub login
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: gabbium
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push ${{ matrix.name }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ steps.ver.outputs.version }}
          labels: |
            org.opencontainers.image.version=${{ steps.ver.outputs.version }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.release.published_at }}
