name: Publish Docker Images

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ledger-api
            image: gabbium/fintrack-ledger-api
            context: ./services/Ledger/src/Fintrack.Ledger.Api
            dockerfile: ./services/Ledger/src/Fintrack.Ledger.Api/Dockerfile

          - name: ledger-worker-maintenance
            image: gabbium/fintrack-ledger-worker-maintenance
            context: ./services/Ledger/src/Fintrack.Ledger.Worker.Maintenance
            dockerfile: ./services/Ledger/src/Fintrack.Ledger.Worker.Maintenance/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: ver
        run: |
          RAW="${GITHUB_REF_NAME}"
          echo "raw=${RAW}" >> $GITHUB_OUTPUT
          echo "version=${RAW#v}" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: gabbium
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ steps.ver.outputs.version }}
          labels: |
            org.opencontainers.image.version=${{ steps.ver.outputs.version }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
