// <auto-generated />
#nullable disable

using Fintrack.Ledger.Infrastructure.Data;

namespace Fintrack.Ledger.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20250913223823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ledger")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
